CMakeLists.txt: respect libdir
:Release Notes:
Use libdir instead of just 'lib' for destination.

:Detailed Notes:
With aarch64:
  # $BASE_LIB_tune-aarch64 [2 operations]
  #   set meta-webos-pro/conf/machine/include/webos-tune-aarch64.inc:31
  #     "lib64"
  #   override[be]:set /meta-webos-pro/conf/machine/include/webos-tune-aarch64.inc:32
  #     "lib64"
  # pre-expansion value:
  #   "lib64"
  BASE_LIB_tune-aarch64="lib64"

we have:

  # $libdir [4 operations]
  #   exported oe-core/meta/conf/bitbake.conf:46
  #     [export] "1"
  #   set oe-core/meta/conf/bitbake.conf:46
  #     "${exec_prefix}/${baselib}"
  #   override[native]:set oe-core/meta/conf/bitbake.conf:60
  #     "${prefix_native}/lib"
  #   override[nativesdk]:set oe-core/meta/conf/bitbake.conf:72
  #     "${prefix_nativesdk}/lib"
  # pre-expansion value:
  #   "${exec_prefix}/${baselib}"
  export libdir="/usr/lib64"

  # $FILES_tflite-auto-delegation-dev [4 operations]
  #   set oe-core/meta/conf/bitbake.conf:320
  #     "${includedir} ${FILES_SOLIBSDEV} ${libdir}/*.la                 ${libdir}/*.o ${libdir}/pkgconfig ${datadir}/pkgconfig                 ${datadir}/aclocal ${base_libdir}/*.o                 ${libdir}/${BPN}/*.la ${base_libdir}/*.la                 ${libdir}/cmake ${datadir}/cmake"
  #   set meta-webos-pro/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb:35
  #     ""
  #   append meta-webos-pro/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb:39
  #     "${includedir}/* ${libdir}/pkgconfig"
  #   rename from FILES_${PN}-dev data.py:104 [expandKeys]
  #     " ${includedir}/* ${libdir}/pkgconfig"
  # pre-expansion value:
  #   " ${includedir}/* ${libdir}/pkgconfig"
  FILES_tflite-auto-delegation-dev=" /usr/include/* /usr/lib64/pkgconfig"

but CMake will install it in /usr/lib/pkgconfig causing:

  ERROR: tflite-auto-delegation-1.0.0-12-r1 do_package: QA Issue: tflite-auto-delegation: Files/directories were installed but not shipped in any package:
    /usr/lib
    /usr/lib/pkgconfig
    /usr/lib/pkgconfig/auto-delegation.pc
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  tflite-auto-delegation: 3 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-8076] CCC: Various build fixes

Change-Id: I4dbd8025c876325be202555b4f666f3cb03fca55
Reviewed-on: http://gpro.lge.com/c/webos-pro/tflite-auto-delegation/+/333135
Reviewed-by: <martin2.jansa@lgepartner.com>
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: <yeseul.joo@lge.com>
Tested-by: <yeseul.joo@lge.com>